name: Java CI with npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_test:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Lint
        run: |
          npm install
          npm ci
#          npm test
  build_and_test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          npm ci
          npm run build --if-present

  build_push_docker:
    runs-on: self-hosted
    name: Deploy docker
    steps:
#       - name: Login to Github Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ secret.GHCR_USERNAME }}
#           password: ${{ secret.GHCR_PASSWORD }}
      - name: Build image
        uses: action/build-push-action@v2
        with:
          push: true
          tags: latest
          file: ./Dockerfile
#       - name: Push
#         run: |
#           npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
