name: Java CI with npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  code_analysis:
    runs-on: ubuntu-latest
    name: Sonar
    steps:
      - name: Setup
        uses: warchant/setup-sonar-scanner@v3      
    env:    
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
#   build_test:
#     runs-on: ubuntu-latest
#     name: Lint
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v2
#       - name: Setup NodeJS
#         uses: actions/setup-node@v2
#         with:
#           node-version: 12
#       - name: Lint
#         run: |
#           npm install
#           npm ci
#           npm run build --if-present
#           npm test

#   build_push_docker:
#     runs-on: ubuntu-latest
#     name: Deploy docker
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v2
#       - name: Docker login
#         run: docker login docker.pkg.github.com --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
#       - name: Build image
#         run: docker build -t docker.pkg.github.com/vranajozef/node-sample/nodesampleimage:latest .
#       - name: Push image
#         run: docker push docker.pkg.github.com/vranajozef/node-sample/nodesampleimage:latest
